import { chromium, expect } from '@playwright/test';
import { mkdir, writeFile } from 'node:fs/promises';
const out = '.asset-build/review/interactive-story';
await mkdir(out,{recursive:true});
const results=[];
for (const view of [{name:'mobile',width:390,height:844},{name:'desktop',width:1440,height:900},{name:'reduced',width:430,height:932}]) {
  const browser=await chromium.launch({args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
  try {
    const context=await browser.newContext({viewport:{width:view.width,height:view.height},isMobile:view.name!=='desktop',hasTouch:view.name!=='desktop',reducedMotion:view.name==='reduced'?'reduce':'no-preference',recordVideo:{dir:out,size:{width:view.width,height:view.height}}});
    const page=await context.newPage();page.setDefaultTimeout(15000);const errors=[];const requests=[];
    page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));
    const shot=async name=>{await page.screenshot({path:`${out}/${view.name}-${name}.png`});console.log(`${view.name}: ${name}`);};
    await page.goto('http://127.0.0.1:5173/birthday-card/');
    await page.getByRole('button',{name:'打开这份惊喜'}).waitFor();await shot('invitation');
    await page.getByRole('button',{name:'打开这份惊喜'}).click();
    await page.getByRole('button',{name:'摸摸杏杏'}).click();
    await expect(page.locator('.live-pets-caption')).toContainText('摇了摇尾巴');await shot('pets');
    await page.getByRole('button',{name:/翻开小小美好/}).click();
    await expect(page.locator('.memories-chapter')).toBeVisible();await shot('album');
    await page.getByRole('button',{name:'下一章 →'}).click();
    await page.locator('.accompaniment__keys').waitFor();
    const key=page.getByRole('button',{name:'弹奏来',exact:true});
    await key.scrollIntoViewIfNeeded();await key.focus();await page.keyboard.down('Space');
    await expect(page.locator('.key.is-held')).toHaveCount(1);await page.waitForTimeout(300);await page.keyboard.up('Space');
    await expect(page.locator('.key.is-held')).toHaveCount(0);await shot('piano');
    await page.getByRole('button',{name:/想先看看写给你的话/}).click();
    await expect(page.locator('.letter-paper')).toBeVisible();await shot('letter');
    await page.getByRole('button',{name:/最后，一起许个愿/}).click();
    const savanna=page.locator('.savanna-story');await expect(savanna).toBeVisible();
    await savanna.scrollIntoViewIfNeeded();await page.getByRole('button',{name:'轻轻招呼幼狮'}).click();
    await expect(savanna).toHaveAttribute('data-motion','approach');await shot('dawn');
    await page.locator('.savanna-chapters button').nth(1).click();
    for(let i=1;i<=3;i++) await page.getByRole('button',{name:`点亮第${i}颗星`,exact:true}).click();
    await expect(savanna.locator('.savanna-star-controls [aria-pressed=true]')).toHaveCount(3);await shot('stars');
    await page.locator('.savanna-chapters button').nth(2).click();
    const walk=page.getByRole('button',{name:'按住，向前走'});await walk.scrollIntoViewIfNeeded();await walk.focus();
    await page.keyboard.down('Space');await page.waitForTimeout(450);await page.keyboard.up('Space');
    await expect(savanna).toHaveAttribute('data-motion','idle');
    const position=await savanna.getAttribute('data-progress');expect(Number(position)).toBeGreaterThan(0);
    await page.waitForTimeout(350);expect(await savanna.getAttribute('data-progress')).toBe(position);
    await page.getByRole('button',{name:'勇敢地吼一声'}).click();await expect(savanna).toHaveAttribute('data-motion','roar');await shot('return');
    await page.getByRole('button',{name:/把这份勇气/}).click();
    await expect(page.locator('.cinema-cake')).toBeVisible();await shot('cake');
    await page.getByRole('button',{name:'许下愿望，轻轻熄灭生日蜡烛'}).click();
    await expect(page.locator('.final-wish')).toHaveAttribute('data-candle-state','complete',{timeout:20000});
    await expect(page.locator('.cinema-cake')).toBeVisible();await shot('ending');
    await page.getByRole('button',{name:'重读那封信',exact:true}).click();await expect(page.locator('.letter-paper')).toBeVisible();
    expect(errors).toEqual([]);
    expect(requests.filter(url=>/cinema\/.*\.mp4/.test(url))).toEqual([]);
    expect(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth+1)).toBe(true);
    results.push({view:view.name,pass:true,pageErrors:errors,coreFilmRequests:0,recording:await page.video().path()});
    await context.close();console.log(`PASS ${view.name}: all chapters, pet, piano, stars, walk/release, roar, retained cake, reread, no film requests.`);
  } finally {await browser.close();}
}
await writeFile(`${out}/results.json`,JSON.stringify(results,null,2));
