import { chromium } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
const out='.asset-build/review/keyframes';await mkdir(out,{recursive:true});
const browser=await chromium.launch({args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try {
 const page=await browser.newPage({viewport:{width:430,height:932},isMobile:true,hasTouch:true});
 await page.goto('http://127.0.0.1:5173/birthday-card/');
 await page.getByRole('button',{name:'打开这份惊喜'}).waitFor();
 await page.screenshot({path:`${out}/01-invitation.png`});
 await page.getByRole('button',{name:'打开这份惊喜'}).click();
 const pets=page.locator('.live-pets');await pets.scrollIntoViewIfNeeded();
 await page.locator('.live-pets-stage[data-ready=true]').waitFor();await page.waitForTimeout(800);
 await pets.screenshot({path:`${out}/pets.png`});
 await page.getByRole('button',{name:/翻开小小美好/}).click();
 await page.locator('.memories-chapter').waitFor();await page.waitForTimeout(1200);
 await page.locator('.memories-chapter').screenshot({path:`${out}/02-album.png`});
 await page.getByRole('button',{name:'下一章 →'}).click();
 await page.locator('.duet-stage__viewport canvas').waitFor();await page.waitForTimeout(3000);
 await page.locator('.duet-sequence').screenshot({path:`${out}/03-piano.png`});
 await page.getByRole('button',{name:/想先看看写给你的话/}).click();
 await page.getByRole('button',{name:/最后，一起许个愿/}).click();
 await page.locator('.savanna-frame').waitFor();await page.waitForTimeout(1200);
 await page.locator('.savanna-frame').screenshot({path:`${out}/04-savanna.png`});
 await page.locator('.savanna-chapters button').nth(2).click();
 await page.getByRole('button',{name:/把这份勇气/}).click();
 await page.locator('.cinema-cake canvas').waitFor();await page.waitForTimeout(1500);
 await page.getByRole('button',{name:'许下愿望，轻轻熄灭生日蜡烛'}).click();
 await page.locator('.wish-complete').waitFor();await page.waitForTimeout(6500);
 await page.locator('.final-wish').screenshot({path:`${out}/05-keepsake.png`});
 console.log('Saved current invitation, album, seated piano, savanna, keepsake and pets keyframes.');
} finally { await browser.close(); }
